---
title: "Homework_Rairuoho"
author: "Meng-Hsin, Wu"
date: "2021/10/11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r cars}
rairuoho<-read.table('https://www.dipintothereef.com/uploads/3/7/3/5/37359245/rairuoho.txt', header= T,
           sep= '\t',
            dec= '.')
library(tidyr)
vignette("pivot")
library(dplyr)
rairuoho2<- rairuoho%>%pivot_longer(
   cols= starts_with('day'),
    names_to= 'days',
    names_prefix= 'day',
    names_transform = list(days= as.integer),
    values_to= 'length',
    )
rairuoho3<- rairuoho2%>% select(spatial1, spatial2, days, length, treatment)
rairuoho4<- rairuoho3%>% unite('spatial_coordinates',
                                c(spatial1, spatial2),
                               sep= '_')
rairuoho4$treatment<- ifelse(rairuoho4$treatment== 'nutrient', 'enriched', 'water')
rairuoho4
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
